inherit_gem:
  caliber: config/all.yml

Metrics/ParameterLists:
  Exclude:
    - lib/trmnl/api/models/recipes/meta.rb
    - lib/trmnl/api/requester.rb
Naming/VariableNumber:
  Exclude:
    - lib/trmnl/api/contracts/ip_address.rb
    - lib/trmnl/api/models/ip_address.rb
    - spec/lib/trmnl/api/models/ip_address_spec.rb
Style/IpAddresses:
  Exclude:
    - spec/lib/trmnl/api/types_spec.rb
    - spec/lib/trmnl/api/models/ip_address_spec.rb
    - spec/lib/trmnl/api/endpoints/ip_address_spec.rb
